--- 
- name: Configure L3 Interface
  nxos_config:
    lines:
    - description {{ description }}
    - vrf member {{ vrf }}
    - ip address {{ NXOS3_ip }} tag {{ vrf }}
    - no shutdown
    parents: interface Vlan{{ vlan_id }}
...
