--- 
- name: Configure L3 Interface
  nxos_config:
    lines:
    - description {{ description }}
    - vrf member {{ vrf }}
    - ip address {{ network_ip | ipmath(4) }}{{ prefix }} tag {{ vrf }}
    - no shutdown
    parents: interface Vlan{{ vlan_id }}

- name: Configure HSRP
  nxos_hsrp:
    group: "{{ ((vlan_id % 2)*-1)+2 }}"
    vip: "{{ network_ip | ipmath(1) }}"
    priority: '200'
    interface: Vlan{{ vlan_id }}
    preempt: disabled
    version: '2'
...
