--- 
- name: Configure L3 Interface
  nxos_config:
    lines:
    - description {{ description }}
    - vrf member {{ vrf }}
    - ip address {{ r1_ip }}{{ prefix }} tag {{ vrf }}
    - no shutdown
    parents: interface Vlan{{ vlan_id }}

- name: Configure HSRP
  nxos_hsrp:
    group: "{{ hsrp_grp }}"
    vip: "{{ hsrp_ip }}"
    priority: '200'
    interface: Vlan{{ vlan_id }}
    preempt: disabled
    version: '2'
...
